-- Predefined exercises visible to every user (exercises.is_predefined = true).
-- Runs after migrations on `supabase db reset` (local by default; see
-- supabase/config.toml [db.seed]). Keep in sync with the production
-- exercises table, since predefined rows are not managed via migrations.
insert into public.exercises (name, is_predefined) values
  ('Arnold Press', true),
  ('Back Extension', true),
  ('Back Squat', true),
  ('Ball Slam', true),
  ('Banded TKE', true),
  ('Banded Walk', true),
  ('Bench Press', true),
  ('Bent Row', true),
  ('Bicep Curl', true),
  ('Block Clean', true),
  ('Block Clean and Jerk', true),
  ('Block Power Clean', true),
  ('Block Pull', true),
  ('Block Snatch', true),
  ('Box Jump', true),
  ('Box Squat', true),
  ('Broad Jump', true),
  ('Bulgarian Split Squat', true),
  ('Chest Supported Back Flye', true),
  ('Clean', true),
  ('Clean & Jerk', true),
  ('Clean + Front Squat + Jerk', true),
  ('Clean Deadlift', true),
  ('Clean Lift Off', true),
  ('Clean Pull', true),
  ('Close Grip Bench', true),
  ('Deadlift', true),
  ('Depth Jump', true),
  ('Dumbbell Bench Press', true),
  ('Dumbbell Seated Overhead Press', true),
  ('Dumbbell Single Arm Row', true),
  ('Farmer Carry', true),
  ('French Press', true),
  ('Front Raise', true),
  ('Front Squat', true),
  ('Front Squat + Jerk', true),
  ('GHD Sit-Up', true),
  ('Glute Bridge', true),
  ('Goblet Squat Jump', true),
  ('Hamstring Curl', true),
  ('Handstand Hold', true),
  ('Hang Below Knee Pull', true),
  ('Hang Clean', true),
  ('Hang Kettlebell Snatch', true),
  ('Hang Power Clean', true),
  ('Hang Power Snatch', true),
  ('Hang Snatch', true),
  ('Hanging Leg Raise', true),
  ('Heaving Hang Power Clean', true),
  ('Heaving Hang Power Clean + Split Jerk', true),
  ('Hi-Lo Carry', true),
  ('High Pull', true),
  ('Jerk', true),
  ('Jumping Lunge', true),
  ('Kettlebell Swing', true),
  ('Lateral Raise', true),
  ('Leg Press', true),
  ('Leg Raise', true),
  ('Muscle Snatch', true),
  ('Muscle Snatch + Overhead Squat', true),
  ('Narrow Stance Squat', true),
  ('Overhead Carry', true),
  ('Overhead Press', true),
  ('Overhead Squat', true),
  ('Pause Squat', true),
  ('Plank', true),
  ('Power Clean', true),
  ('Power Clean + Power Jerk', true),
  ('Power Clean + Push Press', true),
  ('Power Clean + Split Jerk', true),
  ('Power Clean and Jerk', true),
  ('Power Jerk', true),
  ('Power Snatch', true),
  ('Pull-Down', true),
  ('Pull-Up', true),
  ('Push Press', true),
  ('Push-Up', true),
  ('Ring Row', true),
  ('Romanian Deadlift', true),
  ('Russian Twist', true),
  ('Side Plank', true),
  ('Sit-Up', true),
  ('Skater Hop', true),
  ('Skull Crusher', true),
  ('Sled Push', true),
  ('Snatch', true),
  ('Snatch + Overhead Squat', true),
  ('Snatch Balance + Overhead Squat', true),
  ('Snatch Deadlift', true),
  ('Snatch Grip Push Press', true),
  ('Snatch Grip Push Press + Overhead Squat', true),
  ('Snatch Pull', true),
  ('Sots Press', true),
  ('Split Jerk', true),
  ('Sprints', true),
  ('Squat Jump', true),
  ('Standing Side Crunch', true),
  ('Suitcase Carry', true),
  ('Sumo Deadlift', true),
  ('Tall Clean', true),
  ('Upright Row', true),
  ('Walking Lunge', true);

-- Local-only test users, already email-confirmed. Password for both: 123456
-- auth.users must be seeded directly (GoTrue has no seed-file mechanism of
-- its own); this fires the on_auth_user_created trigger, which creates the
-- matching public.profiles row for each. Never run this against a linked
-- project — it writes real auth records with a known, shared password.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'a@a.com',
   extensions.crypt('123456', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'b@b.com',
   extensions.crypt('123456', extensions.gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');

insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
select gen_random_uuid(), id, id::text, jsonb_build_object('sub', id::text, 'email', email),
  'email', now(), now(), now()
from auth.users
where email in ('a@a.com', 'b@b.com');
